apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: shared-istiocontrolplane
spec:
  # Docs: https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/
  autoInjection:
    components:
      injector:
        enabled: true
    enabled: true
  cni:
    components:
      namespace: kube-system
      cni:
        enabled: true
    enabled: true
  configManagement:
    components:
      galley:
        enabled: false
    enabled: false
  coreDNS:
    components:
      coreDNS:
        enabled: true
    enabled: true
  gateways:
    components:
      egressGateway:
        enabled: false
      ingressGateway:
        enabled: false
    enabled: false
  policy:
    components:
      policy:
        enabled: false
    enabled: false
  security:
    components:
      certManager:
        enabled: false
      citadel:
        enabled: true
      nodeAgent:
        enabled: false
    enabled: true
  telemetry:
    components:
      telemetry:
        enabled: false
    enabled: false
  trafficManagement:
    components:
      pilot:
        enabled: false
    enabled: false
  values:
    global:
      controlPlaneSecurityEnabled: false
      remotePilotCreateSvcEndpoint: true
      remotePilotAddress: PILOT_ILB_IP
      remotePolicyAddress: POLICY_ILB_IP
      remoteTelemetryAddress: TELEMETRY_ILB_IP
      enableTracing: false
      istioRemote: true
      network: ""
    prometheus:
      enabled: false
    security:
      createMeshPolicy: false
      selfSigned: false
    cni:
      cniBinDir: /home/kubernetes/bin
      excludeNamespaces:
        - istio-system
        - kube-system
  unvalidatedValues:
    cni:
      logLevel: info
